_target_: src.dataset.Dataset
cleaning: null
defaults:
  - preprocessing: ???
  - spelling_normalization: ???
  - split: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"

wic_use_pairs:
  group: ALL
  sample: annotated
path: chiwug_100
standard_split:
  dev:
    - 下海
    - 体系
    - 停业
    - 储粮
    - 出血
    - 包装
    - 宰
    - 急
    - 憋
    - 拐
    - 推出
    - 插秧
    - 机制
    - 浓
    - 消化
    - 涨
    - 滑坡
    - 潜伏
    - 火
    - 灰色
    - 炒
    - 热
    - 熟
    - 留下
    - 病毒
    - 窗口
    - 窗户
    - 紫色
    - 细菌
    - 绿色
    - 腌
    - 言语
    - 起步
    - 软
    - 输血
    - 退役
    - 透明
    - 飞越
    - 骑车
    - 鲜艳
  dev1:
    - 下海
    - 体系
    - 停业
    - 储粮
    - 出血
    - 包装
    - 宰
    - 急
    - 憋
    - 拐
    - 推出
    - 插秧
    - 机制
    - 浓
    - 消化
    - 涨
    - 滑坡
    - 潜伏
    - 火
    - 灰色
    - 炒
    - 热
    - 熟
    - 留下
    - 病毒
    - 窗口
    - 窗户
    - 紫色
    - 细菌
    - 绿色
    - 腌
    - 言语
    - 起步
    - 软
    - 输血
    - 退役
    - 透明
    - 飞越
    - 骑车
    - 鲜艳
  dev2:
    - 下海
    - 体系
    - 停业
    - 储粮
    - 出血
    - 包装
    - 宰
    - 急
    - 憋
    - 拐
    - 推出
    - 插秧
    - 机制
    - 浓
    - 消化
    - 涨
    - 滑坡
    - 潜伏
    - 火
    - 灰色
    - 炒
    - 热
    - 熟
    - 留下
    - 病毒
    - 窗口
    - 窗户
    - 紫色
    - 细菌
    - 绿色
    - 腌
    - 言语
    - 起步
    - 软
    - 输血
    - 退役
    - 透明
    - 飞越
    - 骑车
    - 鲜艳
  full:
    - 下海
    - 体系
    - 停业
    - 储粮
    - 出血
    - 包装
    - 宰
    - 急
    - 憋
    - 拐
    - 推出
    - 插秧
    - 机制
    - 浓
    - 消化
    - 涨
    - 滑坡
    - 潜伏
    - 火
    - 灰色
    - 炒
    - 热
    - 熟
    - 留下
    - 病毒
    - 窗口
    - 窗户
    - 紫色
    - 细菌
    - 绿色
    - 腌
    - 言语
    - 起步
    - 软
    - 输血
    - 退役
    - 透明
    - 飞越
    - 骑车
    - 鲜艳
  test: []
test_on: null
type: dev
url: https://zenodo.org/records/10023263/files/chiwug.zip
