_target_: src.dataset.Dataset
cleaning: null
defaults:
  - _self_
  - preprocessing: ???
  - spelling_normalization: ???
  - split: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"

wic_use_pairs:
  group: ALL
  sample: annotated

path: diawug_112
standard_split:
  dev: []
  full:
    - amarrar_atar
    - argolla
    - banco
    - baúl_maletero
    - bolo
    - botar
    - cartera_bolso
    - chamaco_pibe_chico
    - churro
    - coche_carro
    - flete
    - franela
    - gato
    - guagua_colectivo
    - plomero_fontanero
    - pollera_falda
    - saco
    - sindicar_acusar
    - tinto
    - vaina
    - vereda
    - vidriera_escaparate
    - volante_timón
  test: []
  comedi_dev: []
  comedi_test: []
  dev1: []
  dev2: []
test_on: null
type: test
url: https://zenodo.org/records/14891461/files/diawug.zip
