_target_: src.dataset.Dataset
cleaning: null
defaults:
  - preprocessing: ???
  - spelling_normalization: none
  - split: ???
exclude_annotators: []
groupings:
  - "1"
  - "2"
wic_use_pairs:
  group: ALL
  sample: annotated
path: rusemshift_2_200
standard_split:
  dev:
    - ателье  
    - бескомпромиссность  
    - беспредел  
    - благотворительность  
    - блочный  
    - боевик  
    - ботаник  
    - брезентовый  
    - валюта  
    - валютный  
    - вампир  
    - взлом  
    - вирус  
    - выплеск  
    - высоколобый  
    - вышка  
    - гермафродит  
    - гильдия  
    - гимназия  
    - глянец  
    - гололед  
    - голубой  
    - двушка  
    - дивизион  
    - донорство  
    - драйвер  
    - завязка  
    - загрузка  
    - знамя  
    - игра  
    - инкубатор  
    - исполнитель  
    - карта  
    - классный  
    - корпус  
    - лилипут  
    - ломберный  
    - мгновение  
    - модель  
    - мыло  
    - одежда  
    - однодневка  
    - орбита  
    - осуществимый  
    - пакет  
    - партиец  
    - перестройка  
    - погрешность  
    - подстава  
    - предощущение  
    - приношение  
    - прислуга  
    - приставка  
    - провальный  
    - продукция  
    - раскрутка  
    - рождество  
    - рынок  
    - рыночный  
    - свинцовый  
    - собака  
    - сомнение  
    - стаканчик  
    - стачка  
    - стиль  
    - удвоение  
    - флакон  
    - четырехлетка  
    - эрмитажный  
  dev1:
    - ателье  
    - бескомпромиссность  
    - беспредел  
    - благотворительность  
    - блочный  
    - боевик  
    - ботаник  
    - брезентовый  
    - валюта  
    - валютный  
    - вампир  
    - взлом  
    - вирус  
    - выплеск  
    - высоколобый  
    - вышка  
    - гермафродит  
    - гильдия  
    - гимназия  
    - глянец  
    - гололед  
    - голубой  
    - двушка  
    - дивизион  
    - донорство  
    - драйвер  
    - завязка  
    - загрузка  
    - знамя  
    - игра  
    - инкубатор  
    - исполнитель  
    - карта  
    - классный  
    - корпус  
    - лилипут  
    - ломберный  
    - мгновение  
    - модель  
    - мыло  
    - одежда  
    - однодневка  
    - орбита  
    - осуществимый  
    - пакет  
    - партиец  
    - перестройка  
    - погрешность  
    - подстава  
    - предощущение  
    - приношение  
    - прислуга  
    - приставка  
    - провальный  
    - продукция  
    - раскрутка  
    - рождество  
    - рынок  
    - рыночный  
    - свинцовый  
    - собака  
    - сомнение  
    - стаканчик  
    - стачка  
    - стиль  
    - удвоение  
    - флакон  
    - четырехлетка  
    - эрмитажный    
  dev2:
    - ателье  
    - бескомпромиссность  
    - беспредел  
    - благотворительность  
    - блочный  
    - боевик  
    - ботаник  
    - брезентовый  
    - валюта  
    - валютный  
    - вампир  
    - взлом  
    - вирус  
    - выплеск  
    - высоколобый  
    - вышка  
    - гермафродит  
    - гильдия  
    - гимназия  
    - глянец  
    - гололед  
    - голубой  
    - двушка  
    - дивизион  
    - донорство  
    - драйвер  
    - завязка  
    - загрузка  
    - знамя  
    - игра  
    - инкубатор  
    - исполнитель  
    - карта  
    - классный  
    - корпус  
    - лилипут  
    - ломберный  
    - мгновение  
    - модель  
    - мыло  
    - одежда  
    - однодневка  
    - орбита  
    - осуществимый  
    - пакет  
    - партиец  
    - перестройка  
    - погрешность  
    - подстава  
    - предощущение  
    - приношение  
    - прислуга  
    - приставка  
    - провальный  
    - продукция  
    - раскрутка  
    - рождество  
    - рынок  
    - рыночный  
    - свинцовый  
    - собака  
    - сомнение  
    - стаканчик  
    - стачка  
    - стиль  
    - удвоение  
    - флакон  
    - четырехлетка  
    - эрмитажный    
  full:
    - ателье  
    - бескомпромиссность  
    - беспредел  
    - благотворительность  
    - блочный  
    - боевик  
    - ботаник  
    - брезентовый  
    - валюта  
    - валютный  
    - вампир  
    - взлом  
    - вирус  
    - выплеск  
    - высоколобый  
    - вышка  
    - гермафродит  
    - гильдия  
    - гимназия  
    - глянец  
    - гололед  
    - голубой  
    - двушка  
    - дивизион  
    - донорство  
    - драйвер  
    - завязка  
    - загрузка  
    - знамя  
    - игра  
    - инкубатор  
    - исполнитель  
    - карта  
    - классный  
    - корпус  
    - лилипут  
    - ломберный  
    - мгновение  
    - модель  
    - мыло  
    - одежда  
    - однодневка  
    - орбита  
    - осуществимый  
    - пакет  
    - партиец  
    - перестройка  
    - погрешность  
    - подстава  
    - предощущение  
    - приношение  
    - прислуга  
    - приставка  
    - провальный  
    - продукция  
    - раскрутка  
    - рождество  
    - рынок  
    - рыночный  
    - свинцовый  
    - собака  
    - сомнение  
    - стаканчик  
    - стачка  
    - стиль  
    - удвоение  
    - флакон  
    - четырехлетка  
    - эрмитажный    
  test: []
test_on: null
type: dev
url: https://github.com/Garrafao/RuSemShift.git
commit: 26a113deba172c58bf36d5b0895196d6a7ad38e4
path_in_repo: rusemshift_2/DWUG