_target_: src.dataset.Dataset
cleaning: null
defaults:
  - preprocessing: ???
  - spelling_normalization: none
  - split: ???
exclude_annotators: []
groupings:
  - "1700-1916"
  - "1918-1990"
wic_use_pairs:
  group: ALL
  sample: annotated
path: rushifteval1_200
standard_split:
  dev: []
  test: []
  comedi_dev:
    - дух
    - заблуждение
    - огонь
    - поставщик
    - предательство
    - роспись
    - стол
    - увольнение
    - фаворит
  dev1:
    - авторитет  
    - амбиция  
    - апостол  
    - благодарность  
    - блин  
    - блондин  
    - брат  
    - бригада  
    - веер  
    - век  
    - верховье  
    - возраст  
    - вызов  
    - головка  
    - грех  
    - дух  
    - дядька  
    - дядя  
    - железо  
    - жесть  
    - живот  
    - заблуждение  
    - завод  
    - закладка  
    - земля  
    - издательство  
    - итальянец  
    - кабан  
    - карман  
    - крушение  
    - крыша  
    - кулиса  
    - лечение  
    - линейка  
    - лишение  
    - локоть  
    - лох  
    - любовник  
    - любовь  
    - маньяк  
    - монстр  
    - наволочка  
    - название  
    - наложение  
    - облако  
    - обоснование  
    - огонь  
    - памятник  
    - пафос  
    - писк  
    - план  
    - поколение  
    - половинка  
    - полоса  
    - полость  
    - полукруг  
    - помощник  
    - понедельник  
    - поставщик  
    - поэзия  
    - правда  
    - предательство  
    - прецедент  
    - пролетарий  
    - промышленность  
    - проникновение  
    - прорыв  
    - путь  
    - радикал  
    - размышление  
    - ранец  
    - расчет  
    - риторика  
    - роспись  
    - сверстник  
    - связка  
    - собрат  
    - совершенство  
    - советчик  
    - союзник  
    - список  
    - спутник  
    - ссылка  
    - стена  
    - стипендия  
    - стол  
    - тачка  
    - тупик  
    - увольнение  
    - углеводород  
    - удобство  
    - уклад  
    - университет  
    - установление  
    - фаворит  
    - формат  
    - формула  
    - хозяйка  
    - хор  
    - хрен  
    - цензура  
    - центр  
    - цифра  
    - частица  
    - чек  
    - четверть  
    - штаб  
    - эшелон  
    - юбилей  
    - ядро  
    - ясли  
  dev2:
    - авторитет  
    - амбиция  
    - апостол  
    - благодарность  
    - блин  
    - блондин  
    - брат  
    - бригада  
    - веер  
    - век  
    - верховье  
    - возраст  
    - вызов  
    - головка  
    - грех  
    - дух  
    - дядька  
    - дядя  
    - железо  
    - жесть  
    - живот  
    - заблуждение  
    - завод  
    - закладка  
    - земля  
    - издательство  
    - итальянец  
    - кабан  
    - карман  
    - крушение  
    - крыша  
    - кулиса  
    - лечение  
    - линейка  
    - лишение  
    - локоть  
    - лох  
    - любовник  
    - любовь  
    - маньяк  
    - монстр  
    - наволочка  
    - название  
    - наложение  
    - облако  
    - обоснование  
    - огонь  
    - памятник  
    - пафос  
    - писк  
    - план  
    - поколение  
    - половинка  
    - полоса  
    - полость  
    - полукруг  
    - помощник  
    - понедельник  
    - поставщик  
    - поэзия  
    - правда  
    - предательство  
    - прецедент  
    - пролетарий  
    - промышленность  
    - проникновение  
    - прорыв  
    - путь  
    - радикал  
    - размышление  
    - ранец  
    - расчет  
    - риторика  
    - роспись  
    - сверстник  
    - связка  
    - собрат  
    - совершенство  
    - советчик  
    - союзник  
    - список  
    - спутник  
    - ссылка  
    - стена  
    - стипендия  
    - стол  
    - тачка  
    - тупик  
    - увольнение  
    - углеводород  
    - удобство  
    - уклад  
    - университет  
    - установление  
    - фаворит  
    - формат  
    - формула  
    - хозяйка  
    - хор  
    - хрен  
    - цензура  
    - центр  
    - цифра  
    - частица  
    - чек  
    - четверть  
    - штаб  
    - эшелон  
    - юбилей  
    - ядро  
    - ясли  
  full:
    - авторитет  
    - амбиция  
    - апостол  
    - благодарность  
    - блин  
    - блондин  
    - брат  
    - бригада  
    - веер  
    - век  
    - верховье  
    - возраст  
    - вызов  
    - головка  
    - грех  
    - дух  
    - дядька  
    - дядя  
    - железо  
    - жесть  
    - живот  
    - заблуждение  
    - завод  
    - закладка  
    - земля  
    - издательство  
    - итальянец  
    - кабан  
    - карман  
    - крушение  
    - крыша  
    - кулиса  
    - лечение  
    - линейка  
    - лишение  
    - локоть  
    - лох  
    - любовник  
    - любовь  
    - маньяк  
    - монстр  
    - наволочка  
    - название  
    - наложение  
    - облако  
    - обоснование  
    - огонь  
    - памятник  
    - пафос  
    - писк  
    - план  
    - поколение  
    - половинка  
    - полоса  
    - полость  
    - полукруг  
    - помощник  
    - понедельник  
    - поставщик  
    - поэзия  
    - правда  
    - предательство  
    - прецедент  
    - пролетарий  
    - промышленность  
    - проникновение  
    - прорыв  
    - путь  
    - радикал  
    - размышление  
    - ранец  
    - расчет  
    - риторика  
    - роспись  
    - сверстник  
    - связка  
    - собрат  
    - совершенство  
    - советчик  
    - союзник  
    - список  
    - спутник  
    - ссылка  
    - стена  
    - стипендия  
    - стол  
    - тачка  
    - тупик  
    - увольнение  
    - углеводород  
    - удобство  
    - уклад  
    - университет  
    - установление  
    - фаворит  
    - формат  
    - формула  
    - хозяйка  
    - хор  
    - хрен  
    - цензура  
    - центр  
    - цифра  
    - частица  
    - чек  
    - четверть  
    - штаб  
    - эшелон  
    - юбилей  
    - ядро  
    - ясли  
  comedi_test:
    - авторитет
    - апостол
    - благодарность
    - бригада
    - веер
    - крыша
    - кулиса
    - маньяк
    - монстр
    - название
    - обоснование
    - пафос
    - промышленность
    - ранец
    - ссылка
    - стена
    - тачка
    - университет
    - установление
    - хор
    - хрен
    - штаб
    - ясли
test_on: null
type: dev
url: https://github.com/Garrafao/rushifteval_public.git
commit: 4e9256050e45e51119342a90ef231266e31be5de
path_in_repo: durel/rushifteval1