_target_: src.dataset.Dataset
cleaning: null
defaults:
  - preprocessing: ???
  - spelling_normalization: none
  - split: ???
exclude_annotators: []
groupings:
  - "1700-1916"
  - "1992-2016"
wic_use_pairs:
  group: ALL
  sample: annotated
path: RuSemShift/durel/rushifteval3
standard_split:
  dev:
  - авторитет  
  - амбиция  
  - апостол  
  - благодарность  
  - блин  
  - блондин  
  - брат  
  - бригада  
  - веер  
  - век  
  - верховье  
  - возраст  
  - вызов  
  - головка  
  - грех  
  - дух  
  - дядька  
  - дядя  
  - железо  
  - жесть  
  - живот  
  - заблуждение  
  - завод  
  - закладка  
  - земля  
  - издательство  
  - итальянец  
  - кабан  
  - карман  
  - крушение  
  - крыша  
  - кулиса  
  - лечение  
  - линейка  
  - лишение  
  - локоть  
  - лох  
  - любовник  
  - любовь  
  - маньяк  
  - монстр  
  - наволочка  
  - название  
  - наложение  
  - облако  
  - обоснование  
  - огонь  
  - памятник  
  - пафос  
  - писк  
  - план  
  - поколение  
  - половинка  
  - полоса  
  - полость  
  - полукруг  
  - помощник  
  - понедельник  
  - поставщик  
  - поэзия  
  - правда  
  - предательство  
  - прецедент  
  - пролетарий  
  - промышленность  
  - проникновение  
  - прорыв  
  - путь  
  - радикал  
  - размышление  
  - ранец  
  - расчет  
  - риторика  
  - роспись  
  - сверстник  
  - связка  
  - собрат  
  - совершенство  
  - советчик  
  - союзник  
  - список  
  - спутник  
  - ссылка  
  - стена  
  - стипендия  
  - стол  
  - тачка  
  - тупик  
  - увольнение  
  - углеводород  
  - удобство  
  - уклад  
  - университет  
  - установление  
  - фаворит  
  - формат  
  - формула  
  - хозяйка  
  - хор  
  - хрен  
  - цензура  
  - центр  
  - цифра  
  - частица  
  - чек  
  - четверть  
  - штаб  
  - эшелон  
  - юбилей  
  - ядро  
  - ясли  
  dev1:
    - авторитет  
    - амбиция  
    - апостол  
    - благодарность  
    - блин  
    - блондин  
    - брат  
    - бригада  
    - веер  
    - век  
    - верховье  
    - возраст  
    - вызов  
    - головка  
    - грех  
    - дух  
    - дядька  
    - дядя  
    - железо  
    - жесть  
    - живот  
    - заблуждение  
    - завод  
    - закладка  
    - земля  
    - издательство  
    - итальянец  
    - кабан  
    - карман  
    - крушение  
    - крыша  
    - кулиса  
    - лечение  
    - линейка  
    - лишение  
    - локоть  
    - лох  
    - любовник  
    - любовь  
    - маньяк  
    - монстр  
    - наволочка  
    - название  
    - наложение  
    - облако  
    - обоснование  
    - огонь  
    - памятник  
    - пафос  
    - писк  
    - план  
    - поколение  
    - половинка  
    - полоса  
    - полость  
    - полукруг  
    - помощник  
    - понедельник  
    - поставщик  
    - поэзия  
    - правда  
    - предательство  
    - прецедент  
    - пролетарий  
    - промышленность  
    - проникновение  
    - прорыв  
    - путь  
    - радикал  
    - размышление  
    - ранец  
    - расчет  
    - риторика  
    - роспись  
    - сверстник  
    - связка  
    - собрат  
    - совершенство  
    - советчик  
    - союзник  
    - список  
    - спутник  
    - ссылка  
    - стена  
    - стипендия  
    - стол  
    - тачка  
    - тупик  
    - увольнение  
    - углеводород  
    - удобство  
    - уклад  
    - университет  
    - установление  
    - фаворит  
    - формат  
    - формула  
    - хозяйка  
    - хор  
    - хрен  
    - цензура  
    - центр  
    - цифра  
    - частица  
    - чек  
    - четверть  
    - штаб  
    - эшелон  
    - юбилей  
    - ядро  
    - ясли  
  dev2:
    - авторитет  
    - амбиция  
    - апостол  
    - благодарность  
    - блин  
    - блондин  
    - брат  
    - бригада  
    - веер  
    - век  
    - верховье  
    - возраст  
    - вызов  
    - головка  
    - грех  
    - дух  
    - дядька  
    - дядя  
    - железо  
    - жесть  
    - живот  
    - заблуждение  
    - завод  
    - закладка  
    - земля  
    - издательство  
    - итальянец  
    - кабан  
    - карман  
    - крушение  
    - крыша  
    - кулиса  
    - лечение  
    - линейка  
    - лишение  
    - локоть  
    - лох  
    - любовник  
    - любовь  
    - маньяк  
    - монстр  
    - наволочка  
    - название  
    - наложение  
    - облако  
    - обоснование  
    - огонь  
    - памятник  
    - пафос  
    - писк  
    - план  
    - поколение  
    - половинка  
    - полоса  
    - полость  
    - полукруг  
    - помощник  
    - понедельник  
    - поставщик  
    - поэзия  
    - правда  
    - предательство  
    - прецедент  
    - пролетарий  
    - промышленность  
    - проникновение  
    - прорыв  
    - путь  
    - радикал  
    - размышление  
    - ранец  
    - расчет  
    - риторика  
    - роспись  
    - сверстник  
    - связка  
    - собрат  
    - совершенство  
    - советчик  
    - союзник  
    - список  
    - спутник  
    - ссылка  
    - стена  
    - стипендия  
    - стол  
    - тачка  
    - тупик  
    - увольнение  
    - углеводород  
    - удобство  
    - уклад  
    - университет  
    - установление  
    - фаворит  
    - формат  
    - формула  
    - хозяйка  
    - хор  
    - хрен  
    - цензура  
    - центр  
    - цифра  
    - частица  
    - чек  
    - четверть  
    - штаб  
    - эшелон  
    - юбилей  
    - ядро  
    - ясли  
  full:
    - авторитет  
    - амбиция  
    - апостол  
    - благодарность  
    - блин  
    - блондин  
    - брат  
    - бригада  
    - веер  
    - век  
    - верховье  
    - возраст  
    - вызов  
    - головка  
    - грех  
    - дух  
    - дядька  
    - дядя  
    - железо  
    - жесть  
    - живот  
    - заблуждение  
    - завод  
    - закладка  
    - земля  
    - издательство  
    - итальянец  
    - кабан  
    - карман  
    - крушение  
    - крыша  
    - кулиса  
    - лечение  
    - линейка  
    - лишение  
    - локоть  
    - лох  
    - любовник  
    - любовь  
    - маньяк  
    - монстр  
    - наволочка  
    - название  
    - наложение  
    - облако  
    - обоснование  
    - огонь  
    - памятник  
    - пафос  
    - писк  
    - план  
    - поколение  
    - половинка  
    - полоса  
    - полость  
    - полукруг  
    - помощник  
    - понедельник  
    - поставщик  
    - поэзия  
    - правда  
    - предательство  
    - прецедент  
    - пролетарий  
    - промышленность  
    - проникновение  
    - прорыв  
    - путь  
    - радикал  
    - размышление  
    - ранец  
    - расчет  
    - риторика  
    - роспись  
    - сверстник  
    - связка  
    - собрат  
    - совершенство  
    - советчик  
    - союзник  
    - список  
    - спутник  
    - ссылка  
    - стена  
    - стипендия  
    - стол  
    - тачка  
    - тупик  
    - увольнение  
    - углеводород  
    - удобство  
    - уклад  
    - университет  
    - установление  
    - фаворит  
    - формат  
    - формула  
    - хозяйка  
    - хор  
    - хрен  
    - цензура  
    - центр  
    - цифра  
    - частица  
    - чек  
    - четверть  
    - штаб  
    - эшелон  
    - юбилей  
    - ядро  
    - ясли  
  test: []
test_on: null
type: dev
url: https://github.com/Garrafao/rushifteval_public.git
commit: 4e9256050e45e51119342a90ef231266e31be5de
path_in_repo: durel/rushifteval3